name: merge staging

on:
    push:
        branches:
            - staging
jobs:
    attempt-cherry-pick:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Prepare repository
              run: |
                  git fetch --unshallow;

                  # Download a platform specific version of auto
                  curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.24.0/auto-linux.gz | gunzip > ~/auto
                  # Make auto executable
                  chmod a+x ~/auto

                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"

            - name: restore workspace cache
              uses: actions/cache@master
              id: cache
              with:
                  path: |
                      node_modules
                      packages/*/node_modules
                  key: node-modules-v2-${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('**/yarn.lock', 'patches/*.patch') }}
                  restore-keys: |
                      node-modules-v2-${{ runner.os }}-${{ steps.node-version.outputs.version }}-
                      node-modules-v2-${{ runner.os }}-

            - run: yarn install --frozen-lockfile --network-timeout 9000000
              if: steps.cache.outputs.cache-hit != 'true'
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                  SKIP_DOWNLOAD_MEDIA_ENGINE: true

            - uses: actions-ecosystem/action-get-merged-pull-request@v1
              id: get-merged-pull-request
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Attempt to pick merge commit to stopship branch
              shell: bash {0}
              env:
                  MERGED_PR: ${{ steps.get-merged-pull-request.outputs.number }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # Verify the stopship branch exists
                  REMOTE_EXISTS=`git ls-remote --heads origin stopship`;

                  # If it doesn't create a stopship branch pointing at master
                  if [[ -z $REMOTE_EXISTS ]]; then
                    git checkout main;
                    git checkout -b stopship;
                    git checkout staging;
                  fi

                  MERGED_PR_NUMBER=`git log -1 --pretty=%B | head -1 | sed -r 's/Merge pull request #([0-9]+).*/\1/'`;
                  ~/auto label --pr $MERGED_PR_NUMBER --exists stopship;
                  exit_status=$?;

                  # If the last PR merged has the stopship label
                  if [ $exit_status -eq 0 ]; then
                      COMMIT_TO_PICK=`git rev-parse HEAD`;
                      STOPSHIP_PR=`node ./get-stopship-pr.js`;

                      git checkout stopship;
                      git cherry-pick -m 1 $COMMIT_TO_PICK;
                      exit_status=$?;

                      # Cherry pick successful, try to push commit.
                      if [ $exit_status -eq 0 ]; then
                          git push origin stopship;
                          exit_status=$?;
                      fi

                      # If either cherry pick or push fails, post a comment to the stopship PR alerting maintainers.
                      if [ $exit_status -eq 1 ]; then
                        ~/auto comment --pr $STOPSHIP_PR --context $COMMIT_TO_PICK -m "Automatic cherry pick failed, you will have to manually cherry-pick the merge commit for #$MERGED_PR";
                        exit 1;
                      fi

                      # If there is no stopship PR create one
                      if [[ -z $STOPSHIP_PR ]]; then
                        node ./create-stopship-pr.js
                      fi
                  fi
