name: merge staging

on:
  push:
    branches:
      - staging
jobs:
  attempt-cherry-pick:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Prepare repository
        run: |
          git config --global user.email "hipstersmoothie@users.noreply.github.com"
          git config --global user.name "Andrew Lisowski"

      - name: Attempt to pick merge commit to stopship branch
        shell: bash {0}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git checkout -b test-branch
          touch foo;
          git add foo;
          git commit -m "test commit"
          git push https://${GITHUB_ACTOR}:${GH_TOKEN}@github.com/hipstersmoothie/stopship-actions-test.git test-branch;
