name: merge staging

on:
  push:
    branches:
      - staging
jobs:
  attempt-cherry-pick:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Prepare repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git fetch --unshallow;

          # Download a platform specific version of auto
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.24.0/auto-linux.gz | gunzip > ~/auto
          # Make auto executable
          chmod a+x ~/auto

          git config --global user.email "hipstersmoothie@users.noreply.github.com"
          git config --global user.name "Andrew Lisowski"

      - name: restore workspace cache
        uses: actions/cache@master
        id: cache
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: node-modules-v2-${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('**/yarn.lock', 'patches/*.patch') }}
          restore-keys: |
            node-modules-v2-${{ runner.os }}-${{ steps.node-version.outputs.version }}-
            node-modules-v2-${{ runner.os }}-

      - run: yarn install --frozen-lockfile --network-timeout 9000000
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          SKIP_DOWNLOAD_MEDIA_ENGINE: true

      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Attempt to pick merge commit to stopship branch
        shell: bash {0}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git checkout -b test-branch
          touch foo;
          git add foo;
          git commit -m "test commit"
          git push https://${GITHUB_ACTOR}:${GH_TOKEN}@github.com/hipstersmoothie/stopship-actions-test.git test-branch;
